### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by aplarson** [michaelWagner/foodiegram#2]
The wireframes have an add comment field, but comments don't appear in your schema or workflow. I think they make sense to have

**Comment by michaelWagner** [comment]
Ah yes, I meant to include that, thanks! Changes can be seen [here](https://github.com/michaelWagner/foodiegram/blob/master/docs/schema.md) and [here](https://github.com/michaelWagner/foodiegram#phase-5-user-liking-and-commenting-15-days)
